runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: workdatabase
  CLOUD_SQL_DATABASE_NAME: cinema
  CLOUD_SQL_CONNECTION_NAME: groovy-plating-222519:us-central1:database

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: auto
